# Generated by Django 5.2.5 on 2025-08-24 22:16

import uuid

import apps.authentication.db_mixins
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("domain", models.CharField(blank=True, max_length=255, null=True)),
                ("industry", models.CharField(blank=True, max_length=100, null=True)),
                ("size", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Companies",
                "db_table": "companies",
                "ordering": ["-created_at"],
            },
            bases=(apps.authentication.db_mixins.RetryableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        unique=True,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "password",
                    models.CharField(db_column="password_hash", max_length=255),
                ),
                ("first_name", models.CharField(blank=True, max_length=100, null=True)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("supervisor", "Supervisor"),
                            ("developer", "Developer"),
                        ],
                        default="developer",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                (
                    "date_joined",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        db_column="company_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="authentication.company",
                    ),
                ),
            ],
            options={
                "db_table": "users",
                "ordering": ["-date_joined"],
            },
            bases=(apps.authentication.db_mixins.RetryableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="SupervisedUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "agent_token",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("agent_last_heartbeat", models.DateTimeField(blank=True, null=True)),
                ("agent_config", models.JSONField(blank=True, null=True)),
                ("monitoring_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "supervisor",
                    models.ForeignKey(
                        db_column="supervisor_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supervised_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supervised_relationships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "supervised_users",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user"], name="supervised__user_id_b57395_idx"
                    ),
                    models.Index(
                        fields=["supervisor"], name="supervised__supervi_b7f0f4_idx"
                    ),
                ],
                "unique_together": {("user", "supervisor")},
            },
            bases=(apps.authentication.db_mixins.RetryableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token_hash", models.CharField(max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_sessions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user"], name="user_sessio_user_id_eb20aa_idx"
                    ),
                    models.Index(
                        fields=["token_hash"], name="user_sessio_token_h_e8cef0_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="user_sessio_expires_66ae96_idx"
                    ),
                ],
            },
            bases=(apps.authentication.db_mixins.RetryableModelMixin, models.Model),
        ),
    ]
