# Generated by Django 5.2.5 on 2025-09-10 03:54

import apps.management.db_mixins
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('company_id', models.UUIDField(help_text='Reference to auth.companies.id')),
                ('created_by', models.UUIDField(help_text='Reference to auth.users.id')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'management.teams',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company_id'], name='management._company_17b400_idx'), models.Index(fields=['created_by'], name='management._created_8f5a60_idx'), models.Index(fields=['name'], name='management._name_d690c0_idx')],
            },
            bases=(apps.management.db_mixins.RetryableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('repository_url', models.URLField(blank=True, max_length=500, null=True)),
                ('url', models.URLField(blank=True, help_text='Project URL (e.g., live site)', max_length=500, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(db_column='team_id', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='management.team')),
            ],
            options={
                'db_table': 'management.projects',
                'ordering': ['-created_at'],
            },
            bases=(apps.management.db_mixins.RetryableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(help_text='Reference to auth.users.id')),
                ('role', models.CharField(choices=[('lead', 'Team Lead'), ('developer', 'Developer'), ('senior_developer', 'Senior Developer'), ('junior_developer', 'Junior Developer'), ('intern', 'Intern'), ('designer', 'Designer'), ('qa', 'QA Engineer')], default='developer', max_length=50)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(db_column='team_id', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='management.team')),
            ],
            options={
                'db_table': 'management.team_members',
                'ordering': ['-joined_at'],
            },
            bases=(apps.management.db_mixins.RetryableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('jira', 'Jira'), ('slack', 'Slack'), ('discord', 'Discord'), ('teams', 'Microsoft Teams'), ('trello', 'Trello'), ('asana', 'Asana'), ('jenkins', 'Jenkins'), ('circleci', 'CircleCI'), ('custom', 'Custom Integration')], max_length=50)),
                ('config_data', models.JSONField(default=dict, help_text='Integration-specific configuration data')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='management.project')),
            ],
            options={
                'db_table': 'management.integrations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project'], name='management._project_d87fbb_idx'), models.Index(fields=['type'], name='management._type_a2a57e_idx'), models.Index(fields=['is_active'], name='management._is_acti_863ab6_idx')],
            },
            bases=(apps.management.db_mixins.RetryableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GitHubIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('repository_owner', models.CharField(max_length=255)),
                ('repository_name', models.CharField(max_length=255)),
                ('access_token', models.CharField(help_text='Encrypted GitHub access token', max_length=255)),
                ('webhook_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='github_integrations', to='management.project')),
            ],
            options={
                'db_table': 'management.github_integrations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project'], name='management._project_50c432_idx'), models.Index(fields=['repository_owner', 'repository_name'], name='management._reposit_069036_idx'), models.Index(fields=['is_active'], name='management._is_acti_b15837_idx')],
                'unique_together': {('project', 'repository_owner', 'repository_name')},
            },
            bases=(apps.management.db_mixins.RetryableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CodeCommit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commit_hash', models.CharField(max_length=40)),
                ('author_email', models.EmailField(max_length=254)),
                ('author_name', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('branch', models.CharField(default='main', max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('files_changed', models.IntegerField(default=0)),
                ('insertions', models.IntegerField(default=0)),
                ('deletions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='management.project')),
            ],
            options={
                'db_table': 'management.code_commits',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['project'], name='management._project_4660c2_idx'), models.Index(fields=['commit_hash'], name='management._commit__d97e65_idx'), models.Index(fields=['author_email'], name='management._author__eb420e_idx'), models.Index(fields=['timestamp'], name='management._timesta_5ded97_idx')],
                'unique_together': {('project', 'commit_hash')},
            },
            bases=(apps.management.db_mixins.RetryableModelMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['team'], name='management._team_id_8890f0_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['name'], name='management._name_a7026d_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['created_at'], name='management._created_ada2f8_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['team'], name='management._team_id_4857ca_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['user_id'], name='management._user_id_ab8474_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['role'], name='management._role_e43e8e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together={('team', 'user_id')},
        ),
    ]
