# Generated by Django 4.2.16 on 2025-12-03 20:44

import apps.management.db_mixins
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_fix_admin_log_uuid_compatibility'),
    ]

    operations = [
        # Add User model to Django's migration state but don't create the table
        # This allows admin and token_blacklist to reference it
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # Don't create any tables
            state_operations=[
                migrations.CreateModel(
                    name='User',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('password', models.CharField(db_column='password_hash', max_length=128)),
                        ('email', models.EmailField(max_length=254, unique=True)),
                        ('first_name', models.CharField(blank=True, max_length=150)),
                        ('last_name', models.CharField(blank=True, max_length=150)),
                        ('is_staff', models.BooleanField(default=False)),
                        ('is_active', models.BooleanField(default=True)),
                        ('is_superuser', models.BooleanField(default=False)),
                        ('last_login', models.DateTimeField(blank=True, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                    ],
                    options={
                        'db_table': 'users',
                        'managed': False,
                    },
                ),
            ],
        ),
        # Create ProjectMember table
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(help_text='Reference to auth.users.id')),
                ('role', models.CharField(choices=[('owner', 'Project Owner'), ('contributor', 'Contributor'), ('viewer', 'Viewer')], default='contributor', max_length=50)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='management.project')),
            ],
            options={
                'db_table': 'management.project_members',
                'ordering': ['-joined_at'],
                'indexes': [models.Index(fields=['project'], name='management._project_8f880f_idx'), models.Index(fields=['user_id'], name='management._user_id_531a2e_idx'), models.Index(fields=['role'], name='management._role_f016ab_idx')],
                'unique_together': {('project', 'user_id')},
            },
            bases=(apps.management.db_mixins.RetryableModelMixin, models.Model),
        ),
    ]
