# Generated by Django 4.2.16 on 2025-12-06 01:35

import apps.management.db_mixins
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_add_project_member_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField(db_index=True, help_text='Reference to auth.companies.id', unique=True)),
                ('company_name', models.CharField(help_text='Company name for default password generation', max_length=255)),
                ('deletion_protection_enabled', models.BooleanField(default=False, help_text='Enable deletion protection for agents')),
                ('deletion_password_hash', models.CharField(blank=True, help_text='Hashed deletion password', max_length=255, null=True)),
                ('deletion_password_updated_at', models.DateTimeField(blank=True, help_text='When password was last updated', null=True)),
                ('failed_deletion_attempts', models.IntegerField(default=0, help_text='Count of failed deletion attempts')),
                ('last_failed_attempt_at', models.DateTimeField(blank=True, help_text='Last failed deletion attempt', null=True)),
                ('last_failed_attempt_user', models.CharField(blank=True, help_text='Username/email of last failed attempt', max_length=255, null=True)),
                ('updated_by', models.UUIDField(help_text='User ID who last updated settings')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization Settings',
                'verbose_name_plural': 'Organization Settings',
                'db_table': 'management.organization_settings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company_id'], name='management._company_437272_idx'), models.Index(fields=['deletion_protection_enabled'], name='management._deletio_372093_idx')],
            },
            bases=(apps.management.db_mixins.RetryableModelMixin, models.Model),
        ),
    ]
