# Generated by Django 4.2.16 on 2025-12-24 16:54

import apps.management.db_mixins
import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_organizationsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmember',
            name='role',
            field=models.CharField(choices=[('owner', 'Project Owner'), ('contributor', 'Contributor'), ('viewer', 'Viewer'), ('supervisor', 'Supervisor'), ('developer', 'Developer')], default='contributor', max_length=50),
        ),
        migrations.CreateModel(
            name='ProjectInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inviter_id', models.UUIDField(help_text='Reference to auth.users.id - User who sent the invitation')),
                ('invitee_email', models.EmailField(help_text='Email address of the person being invited', max_length=254)),
                ('role', models.CharField(choices=[('supervisor', 'Supervisor'), ('developer', 'Developer')], default='developer', help_text='Project role for the invited user', max_length=50)),
                ('token', models.CharField(help_text='Unique invitation token', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Invitation expires after 7 days')),
                ('is_accepted', models.BooleanField(default=False, help_text='Whether the invitation has been accepted')),
                ('accepted_at', models.DateTimeField(blank=True, help_text='When the invitation was accepted', null=True)),
                ('accepted_by_id', models.UUIDField(blank=True, help_text='User ID who accepted the invitation', null=True)),
                ('auto_added_to_team', models.BooleanField(default=False, help_text='Whether user was automatically added to team upon acceptance')),
                ('project', models.ForeignKey(db_column='project_id', help_text='Project to which the user is being invited', on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='management.project')),
            ],
            options={
                'db_table': 'management.project_invitations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project'], name='management._project_b401ca_idx'), models.Index(fields=['invitee_email'], name='management._invitee_93f59b_idx'), models.Index(fields=['token'], name='management._token_71ef32_idx'), models.Index(fields=['expires_at'], name='management._expires_5e8951_idx'), models.Index(fields=['inviter_id'], name='management._inviter_e3c02c_idx')],
            },
            bases=(apps.management.db_mixins.RetryableModelMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='projectinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('expires_at__gt', datetime.datetime(2025, 12, 24, 16, 54, 6, 407484, tzinfo=datetime.timezone.utc)), ('is_accepted', False)), fields=('project', 'invitee_email'), name='unique_active_project_invitation'),
        ),
    ]
